---
booktitle: 29th Annual Conference on Learning Theory
shortname: COLT
year: '2016'
volume: 49
published: 2016-06-06
start: 2016-06-23
end: 2016-06-26
sections:
- name: preface
  title: Preface
- name: default
  title: Regular Papers
- name: open
  title: Open Problems
layout: proceedings
series: Proceedings of Machine Learning Research
id: COLT2016
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
editor:
- given: Vitaly
  family: Feldman
- given: Alexander
  family: Rakhlin
- given: Ohad
  family: Shamir
description: |
  29th Annual Conference on Learning Theory
    Held in Columbia University, New York, New York, USA on 23-26 June 2016

  Published as Volume 49 by the Proceedings of Machine Learning Research on 06 June 2016.

  Volume Edited by:
    Vitaly Feldman
    Alexander Rakhlin
    Ohad Shamir

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 23--26 Jun
url: http://proceedings.mlr.press
baseurl: "/v49"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v49
bibtex_copy: true
endnote_copy: true
apa_copy: true
email: ''
conference:
  name: Conference on Learning Theory
  url: http://www.learningtheory.org/colt2016/
  location: Columbia University, New York, New York, USA
  dates:
  - 2016-06-23
  - 2016-06-24
  - 2016-06-25
  - 2016-06-26
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v49.bib
